<?php

namespace App\Console\Commands;

use App\Models\Transaction;
use App\Models\User;
use Illuminate\Console\Command;

class AddFakeTransactions extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'fake:transactions';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Add Fake User and then add fake transactions';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        info("Adding One Fake User");
        $names = [
            'Ayesha',
            'Ahmed',
            'Hareem',
            'Àli',
            'Fatima',
            'Muhammad',
            'Zainab',
            'Usman',
            'Karen',
            'Hassan',
            'Laiba',
            'Talha',
            'Manahil',
            'Hamza',
            'Humna',
            'Umair',
            'Tabinda',
            'Ahmad',
            'Aroush',
            'Bilal',
            'Arooba',
            'Waqas',
            'Mahrukh',
            'Zahid',
            'Leah',
            'Saad',
            'Zee',
            'Zeeshan',
            'P.Alizai',
            'Hammad',
            'Bisma',
            'Ibrahim',
            'Ramsha',
            'Yasir',
            'Huma',
            'Ayan',
            'Kashaf',
            'Rashid',
            'Amna',
            'Saif',
            'Suki',
            'Salman',
            'Eishal',
            'Ismail',
            'Aliza',
            'Zain',
            'Mishael',
            'Amir',
            'Saima',
            'Idrees Khan',
            'Aafea',
            'Rizwan',
            'Dua',
            'Malik',
            'Benish',
            'Muhammad Ali',
            'Saamiya',
            'Adnan',
            'Madhia',
            'Faheem',
            'Aliya',
            'Usama',
            'Kiki',
            'Kamran',
            'Rabab',
            'Kashif',
            'Khudija',
            'Ameer',
            'Sarah',
            'Osman',
            'Abby',
            'Abbas',
            'Hina',
            'Raja',
            'Minahil',
            'Waseem',
            'Faraz',
            'Naila',
            'Khan',
            'Fizza',
            'Sohail',
            'Minahel',
            'Muzammal',
            'Sajida',
            'Mohammad',
            'Rida',
            'Sheraz',
            'Thinker',
            'Faiq',
            'Sahar',
            'Muhammad Roidad Khan',
            'Khadija',
            'Shahzad',
            'Maryam',
            'Junaid',
            'Inaya',
            'Jamayel',
            'Aman',
            'Raza',
            'Sheeza',
            'Naqash',
            'Eman',
            'Fazi',
            'Rabia',
            'Sameer',
            'Ruby',
            'Awab',
            'Anum',
            'Aamir',
            'Kathrine',
            'Osama',
            'Annie',
            'Ayaan',
            'Flower',
            'Aliyan',
            'Maheen',
            'Farid',
            'Alishba',
            'Soban',
            'Aruba',
            'Ranjhoo',
            'Maham',
            'Jamshed',
            'Mizha',
            'Muhammad Kazam',
            'Nazy',
            'Ali Kazmi',
            'Amra',
            'Toqeer',
            'Alexis',
            'Zia',
            'Zarish',
            'Ayun',
            'Amina',
            'Muhammad Nouman',
            'Sidra',
            'Syed Najum',
            'Nerda',
            'Nizam',
            'Mirha',
            'Umer',
            'Fiza',
            'Fahad',
            'Ujalaa',
            'Sarmad',
            'Minz',
            'Farhan',
            'Ajwa',
            'Sher',
            'Tehreem',
            'Shaheryar',
            'Ayeza',
            'Adeel',
            'Noor',
            'Saeed',
            'Areej',
            'Shaharyar',
            'Nemera',
            'Aaqib',
            'Manaal',
            'Christopher',
            'Tehniyat',
            'Arsh',
            'Kiran',
            'Husnain',
            'Sonia',
            'Kdog',
            'Alina',
            'Jams',
            'Adeena',
            'Sam',
            'Swan',
            'Bashir Khan',
            'Aleena',
            'Tanvir',
            'Fal',
            'Uzair',
            'Arooha',
            'Sharif',
            'Ejaz',
            'Javed',
            'Moiz',
            'Naveed Jamal',
            'Ahtisham',
            'Khawaja Shariq',
            'Shafee',
            'Jamal',
            'Zahoor',
            'Nab'
        ];

        $countries = [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo, Democratic Republic of the",
            "Congo, Republic of the",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea, North",
            "Korea, South",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        ];

        $user = new User();
        $name = $names[rand(1, count($names))];
        $user->name = $name;
        $user->username = strtolower($name) . rand(00, 99);
        $user->email = $user->username . '@gmail.com';
        $user->password = bcrypt('$user->username');
        $user->fake = true;
        $user->country = $countries[rand(0, count($countries) - 1)];
        $user->phone = rand(1000000000, 9999999999);
        $user->save();

        // adding deposit transaction for this account
        $depsit = rand(0, 1);
        $amounts = [50, 100, 200, 50, 300, 100, 200, 500, 50, 60, 300, 100, 200, 150, 300, 400, 500, 600, 700, 800, 1000, 2000, 1200, 1050, 1800, 2000, 2500, 2100, 2400];
        if ($depsit) {
            $transaction = Transaction::firstOrCreate([
                'user_id' => $user->id,
                'amount' => $amounts[rand(1, count($amounts))],
                'status' => 'approved',
                'type' => 'deposit',
                'sum' => true,
                'reference' => "Fake Transaction",
            ]);
        } else {
            $transaction = Transaction::firstOrCreate([
                'user_id' => $user->id,
                'amount' => $amounts[rand(1, count($amounts))],
                'status' => 'approved',
                'type' => 'withdraw',
                'sum' => false,
                'reference' => "Fake Transaction",
            ]);
        }
    }
}
